/**
 * Picklists for the enrollment forms.
 *
 * These deliberately mirror `mobile_flutter/lib/features/profile/
 * profile_options.dart` value-for-value. A lead is meant to convert into a
 * real UserProfile later by copying columns across, so if the website offers
 * "Commerce and Business" while the app stores "Commerce & Business", every
 * converted account lands with a value the app's own dropdowns can't render.
 * Keep the two files in sync; when one changes, change both.
 */

export const GENDERS = ["Male", "Female", "Other"] as const;

export const LANGUAGES = [
  "English",
  "Hindi",
  "Tamil",
  "Telugu",
  "Kannada",
  "Malayalam",
  "Bengali",
  "Marathi",
  "Gujarati",
  "Punjabi",
  "Others",
] as const;

/** Merged with the degree-stage picklist (was a separate "Degree" field on
 * the aspirant form) so "what stage are you at" is answered in one field. */
export const QUALIFICATIONS = [
  "Higher Secondary (12th)",
  "UG",
  "PG",
  "MD/MS",
  "DNB",
  "Diploma",
  "Doctorate",
  "DM/MCh",
  "Others",
] as const;

/** All 28 states + 8 union territories, alphabetical (with "Other" kept last
 * as the natural fall-through). "Other" reveals a free-text field on both
 * forms rather than losing the answer for anyone outside this list. */
export const INDIAN_STATES = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Other",
] as const;

/** Every state/UT's own districts, keyed by the exact string used in
 * `INDIAN_STATES` — the city dropdown filters against this instead of one
 * flat nationwide list, so picking "Kerala" doesn't leave "Mumbai" sitting
 * in the city options. "Other" is appended at render time (not stored here)
 * so a state genuinely missing a district still isn't a dead end — see
 * CollegeSearch's own "not in the list is still accepted" precedent. State
 * boundaries/district counts shift occasionally (a few states have split
 * districts further since); this list is current as of when it was
 * written, not pinned to any single official source — the "Other"
 * fallback exists precisely so a stale entry never blocks someone. */
export const STATE_DISTRICTS: Record<string, readonly string[]> = {
  "Andaman and Nicobar Islands": ["Nicobar", "North and Middle Andaman", "South Andaman"],
  "Andhra Pradesh": [
    "Alluri Sitharama Raju", "Anakapalli", "Anantapur", "Annamayya", "Bapatla",
    "Chittoor", "East Godavari", "Eluru", "Guntur", "Kakinada", "Konaseema",
    "Krishna", "Kurnool", "Nandyal", "NTR", "Palnadu", "Parvathipuram Manyam",
    "Prakasam", "Sri Sathya Sai", "Srikakulam", "Tirupati", "Visakhapatnam",
    "Vizianagaram", "West Godavari", "YSR Kadapa", "Nellore",
  ],
  "Arunachal Pradesh": [
    "Anjaw", "Changlang", "Dibang Valley", "East Kameng", "East Siang",
    "Kamle", "Kra Daadi", "Kurung Kumey", "Lepa Rada", "Lohit", "Longding",
    "Lower Dibang Valley", "Lower Siang", "Lower Subansiri", "Namsai",
    "Pakke-Kessang", "Papum Pare", "Shi Yomi", "Siang", "Tawang", "Tirap",
    "Upper Siang", "Upper Subansiri", "West Kameng", "West Siang",
  ],
  Assam: [
    "Baksa", "Barpeta", "Biswanath", "Bongaigaon", "Cachar", "Charaideo",
    "Chirang", "Darrang", "Dhemaji", "Dhubri", "Dibrugarh", "Dima Hasao",
    "Goalpara", "Golaghat", "Hailakandi", "Hojai", "Jorhat", "Kamrup",
    "Kamrup Metropolitan", "Karbi Anglong", "Karimganj", "Kokrajhar",
    "Lakhimpur", "Majuli", "Morigaon", "Nagaon", "Nalbari", "Sivasagar",
    "Sonitpur", "South Salmara-Mankachar", "Tinsukia", "Udalguri",
    "West Karbi Anglong",
  ],
  Bihar: [
    "Araria", "Arwal", "Aurangabad", "Banka", "Begusarai", "Bhagalpur",
    "Bhojpur", "Buxar", "Darbhanga", "East Champaran", "Gaya", "Gopalganj",
    "Jamui", "Jehanabad", "Kaimur", "Katihar", "Khagaria", "Kishanganj",
    "Lakhisarai", "Madhepura", "Madhubani", "Munger", "Muzaffarpur",
    "Nalanda", "Nawada", "Patna", "Purnia", "Rohtas", "Saharsa",
    "Samastipur", "Saran", "Sheikhpura", "Sheohar", "Sitamarhi", "Siwan",
    "Supaul", "Vaishali", "West Champaran",
  ],
  Chandigarh: ["Chandigarh"],
  Chhattisgarh: [
    "Balod", "Baloda Bazar", "Balrampur", "Bastar", "Bemetara", "Bijapur",
    "Bilaspur", "Dantewada", "Dhamtari", "Durg", "Gariaband",
    "Gaurela-Pendra-Marwahi", "Janjgir-Champa", "Jashpur", "Kabirdham",
    "Kanker", "Khairagarh-Chhuikhadan-Gandai", "Kondagaon", "Korba",
    "Koriya", "Mahasamund", "Manendragarh-Chirmiri-Bharatpur",
    "Mohla-Manpur-Ambagarh Chowki", "Mungeli", "Narayanpur", "Raigarh",
    "Raipur", "Rajnandgaon", "Sakti", "Sarangarh-Bilaigarh", "Sukma",
    "Surajpur", "Surguja",
  ],
  "Dadra and Nagar Haveli and Daman and Diu": ["Dadra and Nagar Haveli", "Daman", "Diu"],
  Delhi: [
    "Central Delhi", "East Delhi", "New Delhi", "North Delhi",
    "North East Delhi", "North West Delhi", "Shahdara", "South Delhi",
    "South East Delhi", "South West Delhi", "West Delhi",
  ],
  Goa: ["North Goa", "South Goa"],
  Gujarat: [
    "Ahmedabad", "Amreli", "Anand", "Aravalli", "Banaskantha", "Bharuch",
    "Bhavnagar", "Botad", "Chhota Udepur", "Dahod", "Dang",
    "Devbhoomi Dwarka", "Gandhinagar", "Gir Somnath", "Jamnagar",
    "Junagadh", "Kheda", "Kutch", "Mahisagar", "Mehsana", "Morbi",
    "Narmada", "Navsari", "Panchmahal", "Patan", "Porbandar", "Rajkot",
    "Sabarkantha", "Surat", "Surendranagar", "Tapi", "Vadodara", "Valsad",
  ],
  Haryana: [
    "Ambala", "Bhiwani", "Charkhi Dadri", "Faridabad", "Fatehabad",
    "Gurugram", "Hisar", "Jhajjar", "Jind", "Kaithal", "Karnal",
    "Kurukshetra", "Mahendragarh", "Nuh", "Palwal", "Panchkula", "Panipat",
    "Rewari", "Rohtak", "Sirsa", "Sonipat", "Yamunanagar",
  ],
  "Himachal Pradesh": [
    "Bilaspur", "Chamba", "Hamirpur", "Kangra", "Kinnaur", "Kullu",
    "Lahaul and Spiti", "Mandi", "Shimla", "Sirmaur", "Solan", "Una",
  ],
  "Jammu and Kashmir": [
    "Anantnag", "Bandipora", "Baramulla", "Budgam", "Doda", "Ganderbal",
    "Jammu", "Kathua", "Kishtwar", "Kulgam", "Kupwara", "Poonch",
    "Pulwama", "Rajouri", "Ramban", "Reasi", "Samba", "Shopian",
    "Srinagar", "Udhampur",
  ],
  Jharkhand: [
    "Bokaro", "Chatra", "Deoghar", "Dhanbad", "Dumka", "East Singhbhum",
    "Garhwa", "Giridih", "Godda", "Gumla", "Hazaribagh", "Jamtara",
    "Khunti", "Koderma", "Latehar", "Lohardaga", "Pakur", "Palamu",
    "Ramgarh", "Ranchi", "Sahebganj", "Seraikela Kharsawan", "Simdega",
    "West Singhbhum",
  ],
  Karnataka: [
    "Bagalkot", "Ballari", "Belagavi", "Bengaluru Rural", "Bengaluru Urban",
    "Bidar", "Chamarajanagar", "Chikballapur", "Chikkamagaluru",
    "Chitradurga", "Dakshina Kannada", "Davanagere", "Dharwad", "Gadag",
    "Hassan", "Haveri", "Kalaburagi", "Kodagu", "Kolar", "Koppal",
    "Mandya", "Mysuru", "Raichur", "Ramanagara", "Shivamogga", "Tumakuru",
    "Udupi", "Uttara Kannada", "Vijayanagara", "Vijayapura", "Yadgir",
  ],
  Kerala: [
    "Alappuzha", "Ernakulam", "Idukki", "Kannur", "Kasaragod", "Kollam",
    "Kottayam", "Kozhikode", "Malappuram", "Palakkad", "Pathanamthitta",
    "Thiruvananthapuram", "Thrissur", "Wayanad",
  ],
  Ladakh: ["Kargil", "Leh"],
  Lakshadweep: ["Lakshadweep"],
  "Madhya Pradesh": [
    "Agar Malwa", "Alirajpur", "Anuppur", "Ashoknagar", "Balaghat",
    "Barwani", "Betul", "Bhind", "Bhopal", "Burhanpur", "Chhatarpur",
    "Chhindwara", "Damoh", "Datia", "Dewas", "Dhar", "Dindori", "Guna",
    "Gwalior", "Harda", "Hoshangabad (Narmadapuram)", "Indore", "Jabalpur",
    "Jhabua", "Katni", "Khandwa", "Khargone", "Maihar", "Mandla",
    "Mandsaur", "Morena", "Narsinghpur", "Neemuch", "Niwari", "Pandhurna",
    "Panna", "Raisen", "Rajgarh", "Ratlam", "Rewa", "Sagar", "Satna",
    "Sehore", "Seoni", "Shahdol", "Shajapur", "Sheopur", "Shivpuri",
    "Sidhi", "Singrauli", "Tikamgarh", "Ujjain", "Umaria", "Vidisha",
  ],
  Maharashtra: [
    "Ahmednagar", "Akola", "Amravati", "Chhatrapati Sambhajinagar", "Beed",
    "Bhandara", "Buldhana", "Chandrapur", "Dharashiv", "Dhule",
    "Gadchiroli", "Gondia", "Hingoli", "Jalgaon", "Jalna", "Kolhapur",
    "Latur", "Mumbai City", "Mumbai Suburban", "Nagpur", "Nanded",
    "Nandurbar", "Nashik", "Palghar", "Parbhani", "Pune", "Raigad",
    "Ratnagiri", "Sangli", "Satara", "Sindhudurg", "Solapur", "Thane",
    "Wardha", "Washim", "Yavatmal",
  ],
  Manipur: [
    "Bishnupur", "Chandel", "Churachandpur", "Imphal East", "Imphal West",
    "Jiribam", "Kakching", "Kamjong", "Kangpokpi", "Noney", "Pherzawl",
    "Senapati", "Tamenglong", "Tengnoupal", "Thoubal", "Ukhrul",
  ],
  Meghalaya: [
    "East Garo Hills", "East Jaintia Hills", "East Khasi Hills",
    "Eastern West Khasi Hills", "North Garo Hills", "Ri Bhoi",
    "South Garo Hills", "South West Garo Hills", "South West Khasi Hills",
    "West Garo Hills", "West Jaintia Hills", "West Khasi Hills",
  ],
  Mizoram: [
    "Aizawl", "Champhai", "Hnahthial", "Khawzawl", "Kolasib", "Lawngtlai",
    "Lunglei", "Mamit", "Saiha", "Saitual", "Serchhip",
  ],
  Nagaland: [
    "Chumoukedima", "Dimapur", "Kiphire", "Kohima", "Longleng",
    "Mokokchung", "Mon", "Niuland", "Noklak", "Peren", "Phek", "Shamator",
    "Tseminyu", "Tuensang", "Wokha", "Zunheboto",
  ],
  Odisha: [
    "Angul", "Balangir", "Balasore", "Bargarh", "Bhadrak", "Boudh",
    "Cuttack", "Deogarh", "Dhenkanal", "Gajapati", "Ganjam",
    "Jagatsinghpur", "Jajpur", "Jharsuguda", "Kalahandi", "Kandhamal",
    "Kendrapara", "Kendujhar", "Khordha", "Koraput", "Malkangiri",
    "Mayurbhanj", "Nabarangpur", "Nayagarh", "Nuapada", "Puri", "Rayagada",
    "Sambalpur", "Subarnapur", "Sundargarh",
  ],
  Puducherry: ["Karaikal", "Mahe", "Puducherry", "Yanam"],
  Punjab: [
    "Amritsar", "Barnala", "Bathinda", "Faridkot", "Fatehgarh Sahib",
    "Fazilka", "Ferozepur", "Gurdaspur", "Hoshiarpur", "Jalandhar",
    "Kapurthala", "Ludhiana", "Malerkotla", "Mansa", "Moga", "Muktsar",
    "Pathankot", "Patiala", "Rupnagar", "SAS Nagar (Mohali)",
    "Shaheed Bhagat Singh Nagar", "Sangrur", "Tarn Taran",
  ],
  Rajasthan: [
    "Ajmer", "Alwar", "Banswara", "Baran", "Barmer", "Bharatpur",
    "Bhilwara", "Bikaner", "Bundi", "Chittorgarh", "Churu", "Dausa",
    "Dholpur", "Dungarpur", "Hanumangarh", "Jaipur", "Jaisalmer", "Jalore",
    "Jhalawar", "Jhunjhunu", "Jodhpur", "Karauli", "Kota", "Nagaur",
    "Pali", "Pratapgarh", "Rajsamand", "Sawai Madhopur", "Sikar",
    "Sirohi", "Sri Ganganagar", "Tonk", "Udaipur",
  ],
  Sikkim: ["East Sikkim", "North Sikkim", "Pakyong", "Soreng", "South Sikkim", "West Sikkim"],
  "Tamil Nadu": [
    "Ariyalur", "Chengalpattu", "Chennai", "Coimbatore", "Cuddalore",
    "Dharmapuri", "Dindigul", "Erode", "Kallakurichi", "Kancheepuram",
    "Kanyakumari", "Karur", "Krishnagiri", "Madurai", "Mayiladuthurai",
    "Nagapattinam", "Namakkal", "Nilgiris", "Perambalur", "Pudukkottai",
    "Ramanathapuram", "Ranipet", "Salem", "Sivaganga", "Tenkasi",
    "Thanjavur", "Theni", "Thoothukudi", "Tiruchirappalli", "Tirunelveli",
    "Tirupathur", "Tiruppur", "Tiruvallur", "Tiruvannamalai", "Tiruvarur",
    "Vellore", "Viluppuram", "Virudhunagar",
  ],
  Telangana: [
    "Adilabad", "Bhadradri Kothagudem", "Hanamkonda", "Hyderabad",
    "Jagtial", "Jangaon", "Jayashankar Bhupalpally", "Jogulamba Gadwal",
    "Kamareddy", "Karimnagar", "Khammam", "Komaram Bheem Asifabad",
    "Mahabubabad", "Mahabubnagar", "Mancherial", "Medak",
    "Medchal-Malkajgiri", "Mulugu", "Nagarkurnool", "Nalgonda",
    "Narayanpet", "Nirmal", "Nizamabad", "Peddapalli", "Rajanna Sircilla",
    "Rangareddy", "Sangareddy", "Siddipet", "Suryapet", "Vikarabad",
    "Wanaparthy", "Warangal", "Yadadri Bhuvanagiri",
  ],
  Tripura: [
    "Dhalai", "Gomati", "Khowai", "North Tripura", "Sepahijala",
    "South Tripura", "Unakoti", "West Tripura",
  ],
  "Uttar Pradesh": [
    "Agra", "Aligarh", "Ambedkar Nagar", "Amethi", "Amroha", "Auraiya",
    "Ayodhya", "Azamgarh", "Baghpat", "Bahraich", "Ballia", "Balrampur",
    "Banda", "Barabanki", "Bareilly", "Basti", "Bhadohi", "Bijnor",
    "Budaun", "Bulandshahr", "Chandauli", "Chitrakoot", "Deoria", "Etah",
    "Etawah", "Farrukhabad", "Fatehpur", "Firozabad", "Gautam Buddha Nagar",
    "Ghaziabad", "Ghazipur", "Gonda", "Gorakhpur", "Hamirpur", "Hapur",
    "Hardoi", "Hathras", "Jalaun", "Jaunpur", "Jhansi", "Kannauj",
    "Kanpur Dehat", "Kanpur Nagar", "Kasganj", "Kaushambi",
    "Lakhimpur Kheri", "Kushinagar", "Lalitpur", "Lucknow", "Maharajganj",
    "Mahoba", "Mainpuri", "Mathura", "Mau", "Meerut", "Mirzapur",
    "Moradabad", "Muzaffarnagar", "Pilibhit", "Pratapgarh", "Prayagraj",
    "Raebareli", "Rampur", "Saharanpur", "Sambhal", "Sant Kabir Nagar",
    "Shahjahanpur", "Shamli", "Shravasti", "Siddharthnagar", "Sitapur",
    "Sonbhadra", "Sultanpur", "Unnao", "Varanasi",
  ],
  Uttarakhand: [
    "Almora", "Bageshwar", "Chamoli", "Champawat", "Dehradun", "Haridwar",
    "Nainital", "Pauri Garhwal", "Pithoragarh", "Rudraprayag",
    "Tehri Garhwal", "Udham Singh Nagar", "Uttarkashi",
  ],
  "West Bengal": [
    "Alipurduar", "Bankura", "Birbhum", "Cooch Behar", "Dakshin Dinajpur",
    "Darjeeling", "Hooghly", "Howrah", "Jalpaiguri", "Jhargram",
    "Kalimpong", "Kolkata", "Malda", "Murshidabad", "Nadia",
    "North 24 Parganas", "Paschim Bardhaman", "Paschim Medinipur",
    "Purba Bardhaman", "Purba Medinipur", "Purulia", "South 24 Parganas",
    "Uttar Dinajpur",
  ],
};

/** Time-of-day slots — shared shape for both the aspirant's "when do you
 * want to talk" preference and the mentor's "when am I generally free"
 * availability, so the two sides of a booking speak the same vocabulary.
 * Deliberately time-of-day, not day-of-week — a weekday/weekend picker just
 * has everyone pick weekend, which tells the matching logic nothing. */
export const TIME_SLOTS = [
  "Morning (6 AM - 12 PM)",
  "Afternoon (12 PM - 4 PM)",
  "Evening (4 PM - 8 PM)",
  "Night (8 PM - 11 PM)",
] as const;

export const MENTORSHIP_TIMINGS = TIME_SLOTS;

/** Mentor's "days you're generally free". */
export const AVAILABILITY_WINDOWS = TIME_SLOTS;

/** UserProfile.stream — a mentor's field of study, or an aspirant's field of
 * interest. Uniscope covers every academic field, not just medical. */
export const STREAMS = [
  "Medical",
  "Dental",
  "Engineering",
  "Arts & Humanities",
  "Commerce & Business",
  "Law",
  "Design",
  "Others",
] as const;

export const DEGREES = ["UG", "PG", "MD/MS", "DNB", "Diploma", "Doctorate", "DM/MCh", "Others"] as const;

/** Degree dropdown options for a stream other than Medical, which keeps
 * the full DEGREES list above. Dental and Engineering each get their own
 * stream-specific first/second degree names; every other non-Medical
 * stream (Arts & Humanities, Commerce & Business, Law, Design, Others)
 * falls back to the generic UG/PG list. */
export const DEGREES_BY_STREAM: Record<string, readonly string[]> = {
  Dental: ["BDS", "MDS", "Doctorate", "Others"],
  Engineering: ["B.Tech/B.E", "M.Tech/M.E", "Diploma", "Doctorate", "Others"],
};
export const DEFAULT_NON_MEDICAL_DEGREES = ["UG", "PG", "Doctorate", "Others"] as const;

/** UserProfile.specialization picklist — shown for Medical-stream mentors on
 * any degree except UG (which has no specialization yet). */
export const MEDICAL_SPECIALIZATIONS = [
  "General Medicine",
  "Anaesthesiology",
  "General Surgery",
  "Orthopaedics",
  "Paediatrics",
  "Obstetrics and Gynaecology",
  "Cardiology",
  "Radio Diagnosis",
  "Critical Care Medicine",
  "Ophthalmology",
  "Emergency Medicine",
  "Neurology",
  "Urology",
  "Medical Gastroenterology",
  "Nephrology",
  "Medical Oncology",
  "Respiratory Medicine",
  "Pathology",
  "Surgical Oncology",
  "Radiation Oncology",
  "Otorhinolaryngology (ENT)",
  "Family Medicine",
  "Neuro Surgery",
  "Surgical Gastroenterology",
  "Cardio Vascular & Thoracic Surgery (Direct 6 Years Course)",
  "Neuro Surgery (Direct 6 Years Course)",
  "Reproductive Medicine",
  "Minimal Access Surgery",
  "Arthroplasty",
  "Dermatology, Venereology and Leprosy",
  "Psychiatry",
  "Cardiac Anaesthesia",
  "Spine Surgery",
  "Interventional Cardiology",
  "Clinical Haematology",
  "Endocrinology",
  "Microbiology",
  "Nuclear Medicine",
  "Vascular Surgery",
  "Neonatology",
  "Paediatric Cardiology",
  "Interventional Radiology",
  "Plastic & Reconstructive Surgery",
  "Head & Neck Oncology",
  "Paediatric Hemato-Oncology",
  "Clinical Immunology and Rheumatology",
  "Onco-Anaesthesia",
  "Paediatric Critical Care",
  "Gynaecological Oncology",
  "Biochemistry",
  "Immunohematology and Blood Transfusion",
  "Maternal & Foetal Medicine",
  "Plastic & Reconstructive Surgery (Direct 6 Years Course)",
  "Cardio Vascular & Thoracic Surgery",
  "Neuro Anaesthesia",
  "Cardiac Electrophysiology",
  "Paediatric Surgery (Direct 6 Years Course)",
  "Transplant Anaesthesia",
  "Palliative Medicine",
  "Vitreo Retinal Surgery",
  "Community Medicine",
  "Neurovascular Intervention",
  "Paediatric Anaesthesia",
  "Hand & Micro Surgery",
  "Paediatric Gastroenterology",
  "Pain Medicine",
  "Renal Transplant",
  "Thoracic Surgery",
  "Trauma & Acute Care Surgery",
  "Hospital Administration",
  "Paediatric Nephrology",
  "Paediatric Neurology",
  "Physiology",
  "Sports Medicine",
  "Anatomy",
  "Infectious Diseases",
  "Minimally Invasive Gynaecologic Surgery",
  "Pharmacology",
  "Colorectal Surgery",
  "Forensic Medicine",
  "Minimal Access Urology",
  "Paediatric Surgery",
  "Paediatric Urology",
  "Trauma Anaesthesia & Critical Care",
  "Addiction Psychiatry",
  "Liver Transplantation",
  "Physical Medicine and Rehabilitation",
  "Stroke Medicine",
  "Bariatric Surgery",
  "Breast Imaging",
  "Fetal Radiology",
  "Geriatric Medicine",
  "Medical Genetics",
  "Musculoskeletal Radiology (MSK Radiology)",
  "Paediatric Endocrinology",
  "Child and Adolescent Psychiatry",
  "Paediatric Emergency Medicine",
  "Paediatric Orthopaedics",
] as const;

/** B.Tech/B.E specialization picklist (NBA source list) — same
 * flat, not-tied-to-any-specific-college treatment as
 * MEDICAL_SPECIALIZATIONS for Medical's Doctorate/Others: a
 * SearchableCombobox lets a mentor pick from this list or type a
 * specialization that isn't in it. Only wired up for B.Tech/B.E so
 * far (see FLAT_SPECIALIZATION_LISTS in MentorForm.tsx) — no source
 * list yet for M.Tech/M.E, Diploma, or other Engineering degrees. */
export const ENGINEERING_SPECIALIZATIONS = [
  "Aerodynamic Engineering",
  "Aeronautical Engineering",
  "Aerospace Engineering",
  "Agricultural Engineering",
  "Agriculture Engineering",
  "Applied Electronics And Instrumentation Engineering",
  "Architecture",
  "Artificial Intelligence And Data Science",
  "Automobile Engineering",
  "Biochemical Engineering",
  "Bioinformatics",
  "Biomedical Engineering",
  "Biotechnology",
  "Biotechnology And Biochemical Engineering",
  "CAD/CAM",
  "Carpet And Textile Technology",
  "Cement And Ceramic Technology",
  "Ceramic Engineering",
  "Ceramic Technology",
  "Chemical And Bio Engineering",
  "Chemical And Electrochemical Engineering",
  "Chemical Engineering",
  "Chemical Engineering (Polymer Technology)",
  "Chemical Technology",
  "Civil And Structural Engineering",
  "Civil Engineering",
  "Civil Engineering (CTM)",
  "Civil Engineering (Water Management)",
  "Computer Engineering",
  "Computer Sci. Eng.",
  "Computer Science",
  "Computer Science And Engineering",
  "Computer Science And Information Technology",
  "Computer Science And Technology",
  "Computer Technology",
  "Construction Engineering And Management",
  "Dyestuff Technology",
  "Electrical And Electronics Engineering",
  "Electrical And Instrumentation Engineering",
  "Electrical Engineering",
  "Electrical Engineering (Electronics And Power)",
  "Electronics And Biomedical Engineering",
  "Electronics And Communication Engineering",
  "Electronics And Computer Engineering",
  "Electronics And Computer Science Engineering",
  "Electronics And Electrical Communication Engineering",
  "Electronics And Electrical Engineering",
  "Electronics And Instrumentation Engineering",
  "Electronics And Instrumentation Technology",
  "Electronics And Power Engineering",
  "Electronics And Telecommunication Engineering",
  "Electronics And Telecommunications Engineering",
  "Electronics And Telematics Engineering",
  "Electronics Design Technology",
  "Electronics Engineering",
  "Electronics Instrumentation And Control Engineering",
  "Electronics Telecommunication Engineering",
  "Environmental Engineering",
  "Environmental Science And Technology",
  "Fashion And Apparel Engineering",
  "Fashion Technology",
  "Fibres And Textiles Processing Technology",
  "Fire Technology And Safety",
  "Food Engineering And Technology",
  "Food Processing Technology",
  "Food Technology",
  "Geo-Informatics",
  "Industrial And Production Engineering",
  "Industrial Biotechnology",
  "Industrial Engineering",
  "Industrial Engineering And Management",
  "Industrial Production Engineering",
  "Information Science",
  "Information Science And Engineering",
  "Information Science And Technology",
  "Information Technology",
  "Information Technology And Engineering",
  "Instrumentation And Control Engineering",
  "Instrumentation And Process Control Engineering",
  "Instrumentation Engineering",
  "Instrumentation Technology",
  "Interior Design",
  "Leather Technology",
  "M. Planning (Housing)",
  "Man Made Fibre Technology",
  "Man Made Textile Technology",
  "Manufacturing Engineering",
  "Manufacturing Engineering And Technology",
  "Manufacturing Processes And Automation Engineering",
  "Manufacturing Technology",
  "Marine Engineering",
  "Mechanical And Automation Engineering",
  "Mechanical Engg. [SW]",
  "Mechanical Engineering",
  "Mechanical Engineering (Auto)",
  "Mechanical Engineering (Sandwich Pattern)",
  "Mechanical Engineering (Sandwich)",
  "Mechatronics Engineering",
  "Medical Electronics",
  "Medical Engineering",
  "Medicinal And Pharmaceutical Chemistry",
  "Metallurgical And Material Sciences",
  "Metallurgical And Materials Engineering",
  "Metallurgical Engineering",
  "Metallurgy",
  "Metallurgy And Materials Engineering",
  "Metallurgy And Materials Technology",
  "Mining Engineering",
  "Oil Technology",
  "Oils, Oleochemicals And Surfactants Technology",
  "Paint Technology",
  "Paper Technology",
  "Petrochemical Engineering",
  "Petrochemical Technology",
  "Petroleum Engineering",
  "Petroleum Studies",
  "Pharmaceutical Chemistry And Technology",
  "Pharmaceutical Engineering And Technology",
  "Plastic And Polymer Engineering",
  "Plastics Engineering",
  "Plastics Technology",
  "Polymer Engineering",
  "Polymer Engineering And Technology",
  "Polymer Science And Engineering",
  "Polymer Science And Technology",
  "Polymer Technology",
  "Power Electronics And Drives",
  "Power Systems",
  "Printing Engineering",
  "Printing Engineering And Graphic Communication",
  "Printing Technology",
  "Production And Industrial Engineering",
  "Production Engineering",
  "Production Engineering (SW)",
  "Production Engineering And Management",
  "Rubber And Plastic Technology",
  "Rubber Technology",
  "Safety And Fire Engineering",
  "Structural Engineering",
  "Surface Coating Technology",
  "Telecommunication Engineering",
  "Textile Chemistry",
  "Textile Engineering",
  "Textile Plant Engineering",
  "Textile Technology",
  "Textile Technology (Fashion Technology)",
  "Textile Technology (Textile Chemistry)",
  "Welding Technology",
] as const;

/** M.Tech/M.E specialization picklist (NBA source list) — same flat,
 * not-tied-to-any-specific-college treatment as
 * ENGINEERING_SPECIALIZATIONS above (which is B.Tech/B.E-only), see
 * FLAT_SPECIALIZATION_LISTS in MentorForm.tsx. */
export const PG_ENGINEERING_SPECIALIZATIONS = [
  "Advanced Communication Systems",
  "Advanced Design And Manufacturing",
  "Advanced Electrical Power System",
  "Advanced Manufacturing",
  "Advanced Manufacturing Systems",
  "Advanced Material Science And Technology",
  "Aerodynamic Engineering",
  "Aerospace Engineering",
  "Applied Electronics",
  "Applied Electronics And Instrumentation Engineering",
  "Armament/Combat Vehicles",
  "Automated Manufacturing Systems",
  "Automobile Engineering",
  "Automotive Engineering",
  "Automotive Technology",
  "Biomedical Engineering",
  "Biomedical Instrumentation",
  "Biomedical Signal Processing And Instrumentation",
  "Biometrics And Cyber Security",
  "Bioprocess Technology",
  "Biotechnology",
  "CAD-CAM And Automation",
  "CAD/CAM",
  "Chemical Engineering",
  "Chemical Engineering (Process Modeling And Simulation)",
  "Chemical Plant Design",
  "Chemical Reaction Engineering",
  "Chemical Technology",
  "Civil Engineering",
  "Communication And Information Systems",
  "Communication And Networks",
  "Communication And Signal Processing",
  "Communication Engineering",
  "Communication Engineering And Signal Processing",
  "Communication Systems",
  "Computer Aided Analysis And Design",
  "Computer Aided Design",
  "Computer Aided Design And Manufacture",
  "Computer Aided Design And Manufacturing",
  "Computer Aided Design Manufacture And Automation",
  "Computer Aided Process And Equipment Design",
  "Computer Aided Process Design",
  "Computer Aided Structural Engineering",
  "Computer And Communication Engineering",
  "Computer And Integrated Manufacturing",
  "Computer Engineering",
  "Computer Engineering (Cyber Security)",
  "Computer Integrated Manufacturing",
  "Computer Networking And Engineering",
  "Computer Networks And Information Security",
  "Computer Science",
  "Computer Science And Engineering",
  "Computer Science And Information Security",
  "Construction Engineering And Management",
  "Construction Engineering And Project Management",
  "Construction Management",
  "Construction Technology",
  "Construction Technology And Management",
  "Control And Automation",
  "Control And Industrial Automation",
  "Control And Instrumentation",
  "Control And Instrumentation Engineering",
  "Control Systems",
  "Control Systems Engineering",
  "Control Systems/Embedded Control Systems",
  "Cyber Security",
  "Design And Manufacturing",
  "Design Engineering",
  "Design For Manufacturing",
  "Design Of Mechanical Equipment",
  "Digital Communications",
  "Digital Communications And Networking",
  "Digital Electronics And Advanced Communication",
  "Digital Electronics And Communication Engineering",
  "Digital Electronics And Communication Systems",
  "Digital Systems",
  "Digital Systems And Computer Electronics",
  "Dyestuff Technology",
  "Electrical Drives",
  "Electrical Engineering",
  "Electrical Machines",
  "Electrical Power Engineering",
  "Electrical Power Systems",
  "Electronic Instrumentation",
  "Electronics",
  "Electronics And Communication Engineering",
  "Electronics And Communication Engineering (Communication Systems)",
  "Electronics And Instrumentation Engineering",
  "Electronics Circuits And System Design",
  "Electronics Design And Technology",
  "Electronics Engineering",
  "Electronics Systems And Communication",
  "Embedded And Real Time Systems",
  "Embedded System And VLSI",
  "Embedded System And VLSI Design",
  "Embedded Systems",
  "Energy And Environmental Engineering",
  "Energy Engineering",
  "Energy Engineering And Management",
  "Energy System Analysis And Design",
  "Energy Systems Engineering",
  "Energy Technology",
  "Engineering Design",
  "Engineering Materials",
  "Engineering Structures",
  "Environmental And Water Resource Engineering",
  "Environmental Engineering",
  "Environmental Geomatics",
  "Environmental Management",
  "Environmental Science And Engineering",
  "Environmental Science And Technology",
  "Excavation Engineering",
  "FAT And ASM",
  "Farm Machinery And Power Engineering",
  "Fibres And Textiles Processing Technology",
  "Fluid Mechanics And Heat Transfer",
  "Food Biotechnology",
  "Food Engineering And Technology",
  "Foundry And Forge Technology",
  "Geoinformatics And Its Applications",
  "Geotechnical And Geoenvironmental Energy",
  "Geotechnical Engineering",
  "Green Technology",
  "Guidance And Navigation Control",
  "Guided Missiles",
  "Health Safety And Environment Management",
  "Heat Power Engineering",
  "High Voltage And Insulation Engineering",
  "High Voltage Engineering",
  "Highway Technology",
  "Hydraulic Structure",
  "Hydraulics And Water Resources Engineering",
  "Hydraulics Engineering",
  "Hydro Power Engineering",
  "Hydrology And Water Resources Engineering",
  "Industrial And Production Engineering",
  "Industrial Automation And Robotics",
  "Industrial Biotechnology",
  "Industrial Ceramics",
  "Industrial Design",
  "Industrial Drives And Control",
  "Industrial Electronics",
  "Industrial Engineering",
  "Industrial Engineering And Management",
  "Industrial Materials And Metallurgy",
  "Industrial Metallurgy",
  "Industrial Pollution Control",
  "Industrial Pollution Control Electronics",
  "Industrial Refrigeration And Cryogenics",
  "Industrial Safety",
  "Industrial Safety Engineering",
  "Industrial Structures",
  "Industrial System And Drives",
  "Information Security",
  "Information Technology",
  "Instrumentation And Control",
  "Instrumentation And Control Engineering",
  "Instrumentation And Control Systems",
  "Instrumentation Engineering",
  "Integrated Power Systems",
  "Internal Combustion Engines",
  "Irrigation Water Management",
  "Laser And Electro-Optics",
  "Machine Design",
  "Machine Design And Analysis",
  "Maintenance Engineering",
  "Manufacturing And Automation",
  "Manufacturing Engineering",
  "Manufacturing Science And Engineering",
  "Manufacturing Systems And Engineering",
  "Manufacturing Systems And Management",
  "Manufacturing Technology",
  "Marine Engineering",
  "Marine Structures",
  "Material Engineering",
  "Material Science And Engineering",
  "Materials Engineering",
  "Materials Science",
  "Mechanical Engineering",
  "Mechanical Engineering (Thermal Engineering)",
  "Mechatronics",
  "Medical Electronics",
  "Metallurgical And Materials Engineering",
  "Metallurgy",
  "Micro Electronics",
  "Micro Electronics And VLSI Design",
  "Microelectronics And VLSI Design",
  "Microwave And Television Engineering",
  "Microwave Engineering",
  "Mineral Process Engineering",
  "Mining Engineering",
  "Modeling And Simulation",
  "Nano Technology",
  "Nanotechnology",
  "Network Infrastructure Management",
  "Non-Destructive Testing",
  "Oil, Oleochemicals And Surfactants Technology",
  "Oils, Oleochemicals And Surfactants Technology",
  "Opto Electronics",
  "Perfume And Flavour Technology",
  "Perfumery And Flavour Technology",
  "Petroleum Processing And Petrochemical Engineering",
  "Pharmaceutical Biotechnology",
  "Pharmaceutical Chemistry And Technology",
  "Physical Metallurgy/Materials Engineering",
  "Plant Design",
  "Plastic Engineering",
  "Polymer Engineering And Technology",
  "Power And Energy System",
  "Power And Energy Systems",
  "Power And Energy Systems Engineering",
  "Power Electronics",
  "Power Electronics And Drives",
  "Power Electronics And Electrical Drives",
  "Power Electronics And Machine Drives",
  "Power Electronics And Systems",
  "Power Engineering",
  "Power System And Drives",
  "Power Systems",
  "Power Systems And Power Electronics",
  "Power Systems Engineering",
  "Power Systems/Power Electronics And Power Systems",
  "Printing Technology",
  "Process Control",
  "Process Control And Instrumentation",
  "Process Dynamics And Control",
  "Process Instrumentation",
  "Process Metallurgy",
  "Processing And Food Engineering",
  "Product Design And Commerce",
  "Product Design And Manufacturing",
  "Production And Industrial Engineering",
  "Production Design And Manufacturing",
  "Production Engineering",
  "Production Engineering And Systems Technology",
  "Project Management",
  "Radio Frequency And Microwave Engineering",
  "Refrigeration And Air Conditioning",
  "Remote Sensing",
  "Renewable Energy",
  "Renewable Energy Engineering",
  "Robotics And Automation",
  "Sensor Technology/LEOC",
  "Signal And Image Processing",
  "Signal Processing",
  "Signal Processing And Digital Design",
  "Software Engineering",
  "Soil And Water Conservation Engineering",
  "Soil Mechanics And Foundation Engineering",
  "Stress And Vibration Analysis",
  "Structural Dynamics And Earthquake Engineering",
  "Structural Engineering",
  "Structural Engineering And Construction",
  "Structural Engineering And Construction Management",
  "Surface Coating Technology",
  "System Analysis And Computer Application",
  "Telecommunication Engineering",
  "Textile Technology",
  "Thermal Engineering",
  "Thermal Plant Engineering",
  "Thermal Power Engineering",
  "Thermal Science",
  "Town And Country Planning",
  "Traffic And Transportation Engineering",
  "Transportation Engineering",
  "Transportation Engineering And Management",
  "Turbo Machinery",
  "VLSI",
  "VLSI And Embedded Systems",
  "VLSI Design",
  "VLSI Design And Embedded System",
  "VLSI Design And Embedded Systems",
  "VLSI System Design",
  "VLSI Systems",
  "Water And Environmental Technology",
  "Water Resource Engineering",
  "Water Resources And Hydroinformatics",
  "Water Resources Development And Irrigation Engineering",
  "Water Resources Engineering And Management",
  "Welding Engineering",
  "Wired And Wireless Communication",
  "Wireless And Mobile Communications",
  "Wireless Communications",
] as const;

export const CURRENT_STATUSES = ["Currently Studying", "Graduated"] as const;

/** Some medical/dental degrees run 6 years, so this goes to 6th rather than
 * capping at "5th Year+" the way a typical 4-year UG picklist would. "Intern"
 * covers the compulsory rotatory internship year that follows final-year
 * MBBS/BDS before graduation — not a numbered academic year, but still part
 * of "Currently Studying". */
export const YEARS_OF_STUDY = [
  "1st Year",
  "2nd Year",
  "3rd Year",
  "4th Year",
  "5th Year",
  "6th Year",
  "Intern",
] as const;

/** Past `count` years including the current one, newest first — used for the
 * mentor form's graduation-year picker instead of free-text entry. Computed
 * at render time so it never needs a yearly update. */
export function recentYears(count = 10): number[] {
  const current = new Date().getFullYear();
  return Array.from({ length: count }, (_, i) => current - i);
}

/** Matches the backend's DocumentType enum (`CreateMentorLeadDto.documentType`)
 * — only the display labels below are free to change, the `value`s must stay
 * in sync with the Prisma enum. Labels were genericized (was "NMC
 * registration", medical-only) since mentors now come from every stream. */
export const DOCUMENT_TYPES = [
  { value: "STUDENT_ID", label: "College / Student ID card" },
  { value: "STUDENT_PORTAL_SCREENSHOT", label: "Admission order" },
  { value: "DEGREE_CERTIFICATE", label: "Degree certificate" },
  { value: "NMC_REGISTRATION", label: "Registration certificate" },
] as const;
